coolpup.py data/CLP.cool data/bound_A.bed --outname CLP.bound_A.txt --pad 250 --local
coolpup.py data/DN2.cool data/bound_A.bed --outname DN2.bound_A.txt --pad 250 --local
coolpup.py data/DN3.cool data/bound_A.bed --outname DN3.bound_A.txt --pad 250 --local
coolpup.py data/DN4.cool data/bound_A.bed --outname DN4.bound_A.txt --pad 250 --local
coolpup.py data/DP.cool data/bound_A.bed --outname DP.bound_A.txt --pad 250 --local
coolpup.py data/ETP.cool data/bound_A.bed --outname ETP.bound_A.txt --pad 250 --local
coolpup.py data/CLP.cool data/bound_B.bed --outname CLP.bound_B.txt --pad 250 --local
coolpup.py data/DN2.cool data/bound_B.bed --outname DN2.bound_B.txt --pad 250 --local
coolpup.py data/DN3.cool data/bound_B.bed --outname DN3.bound_B.txt --pad 250 --local
coolpup.py data/DN4.cool data/bound_B.bed --outname DN4.bound_B.txt --pad 250 --local
coolpup.py data/DP.cool data/bound_B.bed --outname DP.bound_B.txt --pad 250 --local
coolpup.py data/ETP.cool data/bound_B.bed --outname ETP.bound_B.txt --pad 250 --local
coolpup.py data/CLP.cool data/bound_C.bed --outname CLP.bound_C.txt --pad 250 --local
coolpup.py data/DN2.cool data/bound_C.bed --outname DN2.bound_C.txt --pad 250 --local
coolpup.py data/DN3.cool data/bound_C.bed --outname DN3.bound_C.txt --pad 250 --local
coolpup.py data/DN4.cool data/bound_C.bed --outname DN4.bound_C.txt --pad 250 --local
coolpup.py data/DP.cool data/bound_C.bed --outname DP.bound_C.txt --pad 250 --local
coolpup.py data/ETP.cool data/bound_C.bed --outname ETP.bound_C.txt --pad 250 --local
coolpup.py data/CLP.cool data/bound_D.bed --outname CLP.bound_D.txt --pad 250 --local
coolpup.py data/DN2.cool data/bound_D.bed --outname DN2.bound_D.txt --pad 250 --local
coolpup.py data/DN3.cool data/bound_D.bed --outname DN3.bound_D.txt --pad 250 --local
coolpup.py data/DN4.cool data/bound_D.bed --outname DN4.bound_D.txt --pad 250 --local
coolpup.py data/DP.cool data/bound_D.bed --outname DP.bound_D.txt --pad 250 --local
coolpup.py data/ETP.cool data/bound_D.bed --outname ETP.bound_D.txt --pad 250 --local
coolpup.py data/CLP.cool data/bound_E.bed --outname CLP.bound_E.txt --pad 250 --local
coolpup.py data/DN2.cool data/bound_E.bed --outname DN2.bound_E.txt --pad 250 --local
coolpup.py data/DN3.cool data/bound_E.bed --outname DN3.bound_E.txt --pad 250 --local
coolpup.py data/DN4.cool data/bound_E.bed --outname DN4.bound_E.txt --pad 250 --local
coolpup.py data/DP.cool data/bound_E.bed --outname DP.bound_E.txt --pad 250 --local
coolpup.py data/ETP.cool data/bound_E.bed --outname ETP.bound_E.txt --pad 250 --local
coolpup.py data/CLP.cool data/bound_F.bed --outname CLP.bound_F.txt --pad 250 --local
coolpup.py data/DN2.cool data/bound_F.bed --outname DN2.bound_F.txt --pad 250 --local
coolpup.py data/DN3.cool data/bound_F.bed --outname DN3.bound_F.txt --pad 250 --local
coolpup.py data/DN4.cool data/bound_F.bed --outname DN4.bound_F.txt --pad 250 --local
coolpup.py data/DP.cool data/bound_F.bed --outname DP.bound_F.txt --pad 250 --local
coolpup.py data/ETP.cool data/bound_F.bed --outname ETP.bound_F.txt --pad 250 --local
coolpup.py data/CLP.cool data/bound_G.bed --outname CLP.bound_G.txt --pad 250 --local
coolpup.py data/DN2.cool data/bound_G.bed --outname DN2.bound_G.txt --pad 250 --local
coolpup.py data/DN3.cool data/bound_G.bed --outname DN3.bound_G.txt --pad 250 --local
coolpup.py data/DN4.cool data/bound_G.bed --outname DN4.bound_G.txt --pad 250 --local
coolpup.py data/DP.cool data/bound_G.bed --outname DP.bound_G.txt --pad 250 --local
coolpup.py data/ETP.cool data/bound_G.bed --outname ETP.bound_G.txt --pad 250 --local
coolpup.py data/CLP.cool data/bound_H.bed --outname CLP.bound_H.txt --pad 250 --local
coolpup.py data/DN2.cool data/bound_H.bed --outname DN2.bound_H.txt --pad 250 --local
coolpup.py data/DN3.cool data/bound_H.bed --outname DN3.bound_H.txt --pad 250 --local
coolpup.py data/DN4.cool data/bound_H.bed --outname DN4.bound_H.txt --pad 250 --local
coolpup.py data/DP.cool data/bound_H.bed --outname DP.bound_H.txt --pad 250 --local
coolpup.py data/ETP.cool data/bound_H.bed --outname ETP.bound_H.txt --pad 250 --local
coolpup.py data/CLP.cool data/bound_J.bed --outname CLP.bound_J.txt --pad 250 --local
coolpup.py data/DN2.cool data/bound_J.bed --outname DN2.bound_J.txt --pad 250 --local
coolpup.py data/DN3.cool data/bound_J.bed --outname DN3.bound_J.txt --pad 250 --local
coolpup.py data/DN4.cool data/bound_J.bed --outname DN4.bound_J.txt --pad 250 --local
coolpup.py data/DP.cool data/bound_J.bed --outname DP.bound_J.txt --pad 250 --local
coolpup.py data/ETP.cool data/bound_J.bed --outname ETP.bound_J.txt --pad 250 --local

plotpup.py CLP.*.txt ETP.*.txt D*.txt --row_names CLP,ETP,DN2,DN3,DN4,DP --col_names A,B,C,D,E,F,G,H,I --n_cols 9 --enrichment 0 --output FigureS2E.pdf
